{
    'name': 'Maena HR Workflow Customization',
    'version': '15.0.1',
    'summary': 'HR Workflow Customizations For Maena Project',
    'description': 'HR Workflow Customizations For Maena Project',
    'category': 'hr',
    'author': 'Hossam Zaki | Pioneer Solutions',
    'depends': ['base',
                'hr_loan_advance',
                'pioneer_HR_Leave',
                'pioneer_hr_clearance',
                'visa_request',
                'air_ticket',
                'hr_overtime_ps',
                'return_from_vacation',
                'pioneer_Business_Trip',
                ],
    'data': [
        'views/hr_loan_advance.xml',
        'views/hr_leave.xml',
        'views/hr_clearance.xml',
        'views/visa_request.xml',
        'views/air_ticket.xml',
        'views/hr_overtime.xml',
        'views/return_from_vacation.xml',
        'views/business_trip.xml',

    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
