{
    'name': 'HR Medical Insurance',
    'version': '15.0.1',
    'summary': 'HR Medical Insurance',
    'description': 'This module manages Medical Insurance & its Providers, Classes',
    'category': 'hr',
    'author': 'Hossam Zaki | Pioneer Solutions',
    'depends': ['base', 'hr', 'ps_mail_bot'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/medical_insurance.xml',
        'views/medical_insurance_provider.xml',
        'views/medical_insurance_class.xml',
        'views/medical_insurance_upgrade.xml',
        'views/hr_employee.xml',
    ],
    'demo': [],
    'sequence': 0,
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
