{
    'name': 'Maena HR Reports',
    'version': '15.0.1',
    'summary': 'Maena HR Reports',
    'description': '',
    'category': 'hr',
    'author': 'Hossam Zaki | Pioneer Solutions',
    'depends': ['base',
                'hr',
                'hr_contract',
                'hr_holidays',
                'pioneer_HR_Leave',
                'ps_mail_bot',
                ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/hr_leave.xml',
        'views/hr_certificate.xml',
        'reports/contract.xml',
        'reports/advance_delay_permission.xml',
        'reports/temporary_period_permission.xml',
        'reports/hr_certificate.xml',

    ],
    'external_dependencies': {'python': ['hijri_converter']},
    'application': False,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
