{
    'name': 'Business Card',
    'version': '15.0.1',
    'summary': 'Business Card',
    'description': '',
    'category': 'hr',
    'author': 'Hossam Zaki | Pioneer Solutions',
    'depends': ['base',
                'hr',
                'hr_contract',
                'alshrooq_employee_details',
                'ps_mail_bot',
                ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/business_card.xml',
        'views/categ_type.xml',

    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
